### ISSUE TITLE
Autowired

### ISSUE THREAD

**Issue by ViniciusLovato** [brunodrugowick/ProgrammingStudies#17]
https://github.com/brunodrugowick/ProgrammingStudies/blob/8e73b107d9b9c7555190c404622cb9fcacb0fd81/UdemySpring5/demo/src/main/java/com/example/demo/controllers/AuthorController.java#L14

Quando existe apenas um constructor pardão não é preciso adicionar a anotação autowired o Spring automaticamente faz a injeção dos objetos passados no construtor

**Comment by brunodrugowick** [comment]
Dá uma olhada nesse commit aqui: https://github.com/brunodrugowick/ProgrammingStudies/commit/46249949d46a9d886b2f07eaebfc1f6b036d450f.

Nesse caso eu anotei explicitamente pra deixar clara a injeção de dependência. Tenho dúvidas se ocultar ou mostrar é o ideal. Dado meu aprendizado, achei melhor deixar explícito pra me lembrar do conceito constantemente.
